name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: humble
            ubuntu: jammy
          - ros: jazzy
            ubuntu: noble
          - ros: rolling
            ubuntu: noble
    name: ROS 2 ${{ matrix.ros }}
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest
    env:
      ROS_DISTRO: ${{ matrix.ros }}
    steps:
      - uses: actions/checkout@v4
      - name: Create dependency repos file
        shell: bash
        run: |
          cat << 'EOF' > /tmp/deps.repos
          {"repositories":
            {"rmw_implementation":
              {"type": "git",
              "url": "https://github.com/BonsaiRobotics/rmw_implementation",
              "version": "${{ matrix.ros }}-bonsai"
              }
            }
          }
          EOF
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros }}
          vcs-repo-file-url: /tmp/deps.repos
          # Not testing rmw_implementation here, with the expectation it's tested at its own home
          package-name: rmw_stats_shim rosgraph_monitor rosgraph_monitor_msgs
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_CXX_FLAGS=\"-Werror\""
                ]
              }
            }
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.ros }}
          path: ros_ws/log
