---

name: pre-commit
"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: sudo apt-get update && sudo apt-get install libxml2-utils
      - uses: pre-commit/action@v3.0.1
